name: Build & Deploy to Server (Reusable)
on:
  workflow_call:
    inputs:
      image_name:
        description: "Image name for GHCR"
        required: true
        type: string
      service_name:
        description: "Service name for deployment"
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set image tag (short commit)
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      #      - name: Determine Node version
      #        id: node_version
      #        run: |
      #          if [ -f .nvmrc ]; then
      #             echo "Using Node version from .nvmrc"
      #             echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      #           else
      #             echo "Using default Node 20.x"
      #             echo "version=20.x" >> $GITHUB_OUTPUT
      #           fi

      #      - name: Setup Node.js
      #        uses: actions/setup-node@v4
      #       with:
      #          node-version: ${{ steps.node_version.outputs.version }}

      #      - name: Install dependencies and build frontend
      #        run: |
      #          npm install
      #          npm run build

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.DOCKERHUB_USER}} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE="ghcr.io/${{ secrets.DOCKERHUB_USER }}/${{ inputs.image_name }}:${{ github.sha }}"
          docker build -t $IMAGE .
          docker push $IMAGE

  deploy:
    runs-on: ${{
      github.ref_name == 'main' && 'edu-runner' ||
      github.ref_name == 'dev' && 'dev-runner'
      }}
    needs: build-and-push
    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.DOCKERHUB_USER}} --password-stdin

      - name: Deploy to Production
        run: |
          docker pull $IMAGE
          docker service update \
            --force \
            --with-registry-auth \
            --detach=false \
            --image $IMAGE \
            ${{ inputs.service_name }}         
          docker container prune -f
